server:
  port: 30601

spring:
  application:
    name: demo-security
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local

alinesno.plat:
  security:
    env: development
    kafkaServers: 192.168.101.18:9092
    user-key: aip@local