server:
  port: 30601

# spring 配置
spring:
  application:
    name: alinesno-infra-plat-security-boot
    id: 1863343810153467904
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_alinesno_infra_plat_security_v100?characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: adminer
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: aip@local
  devtools:
    restart:
      enabled: true

actable:
  table:
    auto: update
  model:
    pack: com.alinesno.infra.plat.security.entity;
  database:
    type: mysql
  index:
    prefix: alinesno_plat_security_idx_
  unique:
    prefix: alinesno_plat_security_uni_

# sa-token配置
sa-token:
  token-name: Authorization
  host-path: http://alinesno-infra-base-identity-auth-application.beta.base.infra.linesno.com
  sso:
    auth-url: ${sa-token.host-path}/login
    is-http: true
    check-ticket-url: ${sa-token.host-path}/sso/checkTicket
    slo-url: ${sa-token.host-path}/sso/signout
    get-data-url: ${sa-token.host-path}/sso/getData
  sign:
    secret-key: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor

# wechat token
alinesno:
  security:
    # 排除路径
    excludes:
      - /sso/**
      - /logout
      - /api/infra/base/platform/provider/**
  infra:
    gateway:
      host: http://alinesno-infra-base-gateway-proxy-application.beta.base.infra.linesno.com